services:
  streamlit:
    build:
      context: .
      dockerfile: docker/dockerfile.streamlit
    container_name: incunabulm-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
